# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
# specific branch
pr:
  branches:
    include:
    - master
    - feature/*

pool:
  name: Default

variables:
- name: PATH
  value: "$PATH:/usr/local/bin"
- name: MOLECULE_SCENARIO_NAME
  value: "podman"
- name: VERIFIER_NAME
  value: "testinfra"

stages:
- stage: ansiblemolecule
  displayName: Ansible Molecule Framework Demo
  # Job list
  jobs:
  - job: ansiblemolecule
    displayName: Ansible Molecule Tests Execution

    steps:
    - script: |
        /usr/local/bin/podman -v
        /usr/local/bin/ansible  --version
        /usr/local/bin/molecule --version
      displayName: 'Display Binaries versions'
    
    - script: |
        molecule -c .config/molecule/config.yml cleanup -s $MOLECULE_SCENARIO_NAME 
        molecule -c .config/molecule/config.yml destroy -s $MOLECULE_SCENARIO_NAME
      workingDirectory: '$(build.sourcesdirectory)'
      displayName: 'Molecule: Clean up environment'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"

    - script: |
        molecule -c .config/molecule/config.yml --debug lint -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Lint all the Ansible Roles/Playbooks'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
        ANSIBLE_REMOTE_PATH: /tmp
        ANSIBLE_REMOTE_TMP: /tmp
        VERIFIER_NAME: "testinfra"  


    - script: |
        molecule -c .config/molecule/config.yml --debug converge -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Create Ephemeral Environment by executing the Ansible Roles/Playbooks'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
        ANSIBLE_REMOTE_PATH: /tmp
        ANSIBLE_REMOTE_TMP: /tmp
        VERIFIER_NAME: "testinfra"  

    - script: |
        molecule -c .config/molecule/config.yml --debug verify -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Run the Testing automation on existing setup'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
        ANSIBLE_REMOTE_PATH: /tmp
        ANSIBLE_REMOTE_TMP: /tmp
        VERIFIER_NAME: "testinfra"  
    
    # - script: |
    #     /usr/local/bin/molecule -c .config/molecule/config.yml --debug test --destroy=never -s $MOLECULE_SCENARIO_NAME
    #   displayName: 'Molecule: Run the full tests'
    #   workingDirectory: '$(build.sourcesdirectory)'
    #   env:
    #     ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
    #     ANSIBLE_REMOTE_PATH: /tmp
    #     ANSIBLE_REMOTE_TMP: /tmp
    #     VERIFIER_NAME: "testinfra"  
