# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
# specific branch
pr:
  branches:
    include:
    - master
    - feature/*

pool:
  name: Default

variables:
- name: ANSIBLE_CONFIG
  value: "$HOME/.ansible.cfg"
- name: PATH
  value: "$PATH:/usr/local/bin"
- name: MOLECULE_SCENARIO_NAME
  value: "podman"
- name: VERIFIER_NAME
  value: "testinfra"

stages:
- stage: checkversion
  displayName: Ansible Molecule Framework Demo
  # Job list
  jobs:
  - job: checkversion
    displayName: Display the tools version

    steps:
    - script: |
        /usr/local/bin/podman -v
        /usr/local/bin/ansible  --version
        /usr/local/bin/molecule --version
      displayName: 'Display Binaries versions'

    - script: |
        molecule -c .config/molecule/config.yml --debug test -s $MOLECULE_SCENARIO_NAME --destroy=never
      displayName: 'Molecule: Test Ansbile Molecule $MOLECULE_SCENARIO_NAME scenario'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
    
  - job: cleanup
    displayName: Clean up the existing Molecule Instances

    steps:
    - script: |
        molecule -c .config/molecule/config.yml cleanup -s $MOLECULE_SCENARIO_NAME 
        molecule -c .config/molecule/config.yml destroy -s $MOLECULE_SCENARIO_NAME
      workingDirectory: '$(build.sourcesdirectory)'
      displayName: 'Molecule: Clean up environment'

  - job: lint
    displayName: Lint all the Ansible Roles/Playbooks
    steps:
    - script: |
        molecule -c .config/molecule/config.yml --debug converge -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Test Ansbile Molecule $MOLECULE_SCENARIO_NAME scenario'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"

  - job: converge
    displayName: Create Ephemeral Environment by executing the Ansible Roles/Playbooks
    steps:
    - script: |
        molecule -c .config/molecule/config.yml --debug converge -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Test Ansbile Molecule $MOLECULE_SCENARIO_NAME scenario'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"

  - job: verify
    displayName: Create Ephemeral Environment by executing the Ansible Roles/Playbooks
    steps:
    - script: |
        molecule -c .config/molecule/config.yml --debug verify -s $MOLECULE_SCENARIO_NAME
      displayName: 'Molecule: Test Ansbile Molecule $MOLECULE_SCENARIO_NAME scenario'
      workingDirectory: '$(build.sourcesdirectory)'
      env:
        ANSIBLE_CONFIG: "$HOME/.ansible.cfg"
