# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

variables:
- name: ANSIBLE_CONFIG
  value: "$HOME/.ansible.cfg"
- name: PATH
  value: "$PATH:/usr/local/bin"
- name: MOLECULE_SCENARIO_NAME
  value: "podman"
- name: VERIFIER_NAME
  value: "testinfra"

steps:
- script: |
    /usr/local/bin/podman -v
    /usr/local/bin/ansible  --version
    /usr/local/bin/molecule --version
  displayName: 'Display versions'

- script: |
    cd ${Build.SourcesDirectory} ; molecule -c .config/molecule/config.yml cleanup -s $MOLECULE_SCENARIO_NAME 
    cd ${Build.SourcesDirectory} ; molecule -c .config/molecule/config.yml destroy -s $MOLECULE_SCENARIO_NAME
  displayName: 'Molecule: Clean up environment'

- script: |
    cd ${Build.SourcesDirectory} ; molecule -c .config/molecule/config.yml test -s $MOLECULE_SCENARIO_NAMEE
  displayName: 'Molecule: Test all the matrix'