---
- name: Converge
  hosts: zookeeper:kafka_broker
  gather_facts: false
  become: true
  # tasks:
  #   - name: Include zookeeper roles
  #     include_role:
  #       name: zookeeper
  #   - name: Include kafka_broker roles
  #     include_role:
  #       name: kafka_broker

- name: Converge zookeeper
  import_playbook: confluent.platform.zookeeper

- name: Converge Kafka Broker
  import_playbook: confluent.platform.kafka_broker
