---
dependency:
  name: galaxy
driver:
  name: azure
platforms:
  - name: azure-centos8
    hostname: confluent
    groups:
      - zookeeper
      - kafka_broker

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        sasl_protocol: plain
        kafka_broker_configure_control_plane_listener: true
        zookeeper_custom_properties:
          dataLogDir: /opt/zookeeper

        kafka_connect_confluent_hub_plugins:
          - jcustenborder/kafka-connect-spooldir:2.0.43

        kafka_connect_connectors:
          - name: sample-connector-1
            config:
              connector.class: "org.apache.kafka.connect.tools.VerifiableSinkConnector"
              tasks.max: "1"
              file: "/etc/kafka/connect-distributed.properties"
              topics: "test_topic"

        zookeeper_service_unit_overrides:
          Description: Custom Zookeeper description

        zookeeper_log4j_root_logger: INFO, zkAppender

        kafka_broker_service_unit_overrides:
          Description: Custom Kafka description

        kafka_broker_log4j_root_logger: "INFO, kafkaAppender"

        schema_registry_log4j_root_logger: INFO, file

        kafka_connect_service_unit_overrides:
          Description: Custom Connect description

        kafka_connect_log4j_root_logger: "INFO, connectAppender"

        kafka_rest_service_unit_overrides:
          Description: Custom Rest Proxy description

        kafka_rest_log4j_root_logger: INFO, file

        ksql_service_unit_overrides:
          Description: Custom KSQLDB description

        ksql_log4j_root_logger: INFO, main

        control_center_service_unit_overrides:
          Description: Custom C3 description

        control_center_log4j_root_logger: INFO, stdout, main

verifier:
  name: ansible
